// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"week04/internal/biz"
	"week04/internal/data"
	"week04/internal/service"
)

// Injectors from wire.go:

func InitializeVideoInfoService() *service.VideoInfoService {
	videoCountStorage := data.NewVideoCountStorage()
	videoMetaStorage := data.NewVideoMetaStorage()
	videoRepo := data.NewVideoRepo(videoCountStorage, videoMetaStorage)
	videoInfoBiz := biz.NewVideoInfoBiz(videoRepo)
	videoInfoService := service.NewVideoInfoService(videoInfoBiz)
	return videoInfoService
}
